### PR TITLE
Warning popup

### PR DESCRIPTION
**Pull request by jsaalfeld**

### CODE REVIEW

**Comment by s-l-teichmann** [comment]
Have you tried to use it in headless mode?

**Comment by dmth** [comment]
No, I've not.

**Comment by s-l-teichmann** [comment]
Please do! :-)

**Comment by dmth** [comment]
Is it worth it? ;)

**Comment by s-l-teichmann** [comment]
The headless codepath is effected. Therefore I would expect that this should be tested, too.

**Comment by dmth** [comment]
Tested. Seems to work, but JobExecutionException should be catched.

**Comment by s-l-teichmann** [comment]
JobExecutionException are always caught by the Processor. In case of the headless mode they will be sent to the log [1].

[1] https://github.com/Intevation/downloadclient/blob/master/src/main/java/de/bayern/gdi/Headless.java#L52

**Pull request merged**
